name: Bug report 🐛
description: Something not working as expected? This is the place to report your issue.
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: |
        # Hi there! :wave:

        Thanks for taking the time to fill out this bug report.

    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into. Please provide screenshots or videos when applicable."
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: 'How do we reproduce the error you described above? Feel free to use the `@primer/react` template on [CodeSandbox](https://codesandbox.io/s/primer-react-qyyepc) to get started'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: In which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
        - iOS Safari
